# Generated by Django 3.1.4 on 2020-12-16 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(choices=[(0, "doesn't matter at all"), (1, 'a little'), (50, 'average'), (250, 'very important'), (999, "don't show my profile to people who selected this")], default=50)),
                ('public_self', models.BooleanField(default=False)),
                ('public_other', models.BooleanField(default=False)),
                ('answer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date answered')),
                ('answer_other', models.ManyToManyField(related_name='answer_other', to='dating.Choice')),
                ('answer_self', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dating.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
