# Generated by Django 3.1.4 on 2020-12-14 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='importance',
            field=models.IntegerField(choices=[(0, "doesn't matter"), (1, 'default importance'), (2, 'very important'), (3, 'absolutely necessary')], default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='about_self',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
