# Generated by Django 3.1.4 on 2020-12-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_auto_20201214_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='about_self',
            field=models.BooleanField(default=False),
        ),
    ]
