# Generated by Django 3.1.4 on 2020-12-17 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dating', '0002_auto_20201217_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreward_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('backward_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('combined_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
