# Generated by Django 3.1.4 on 2020-12-14 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dating', '0003_auto_20201214_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponseOther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(choices=[(0, "doesn't matter"), (1, 'default importance'), (2, 'very important'), (3, 'absolutely necessary')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponseSelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='question',
            name='about_self',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
        migrations.AddField(
            model_name='userresponseself',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating.choice'),
        ),
        migrations.AddField(
            model_name='userresponseself',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating.question'),
        ),
        migrations.AddField(
            model_name='userresponseself',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresponseother',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating.choice'),
        ),
        migrations.AddField(
            model_name='userresponseother',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating.question'),
        ),
        migrations.AddField(
            model_name='userresponseother',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
