# Generated by Django 3.1.4 on 2020-12-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0004_matching_other_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matching',
            old_name='foreward_score',
            new_name='forward_score',
        ),
    ]
