# Generated by Django 3.1.4 on 2020-12-15 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dating', '0006_auto_20201215_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_other', models.ManyToManyField(related_name='answer_other', to='dating.Choice')),
                ('answer_self', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
