# Generated by Django 3.1.4 on 2020-12-15 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0007_auto_20201215_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date answered'),
            preserve_default=False,
        ),
    ]
