# Generated by Django 3.1.4 on 2020-12-15 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0008_answer_answer_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='importance',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='dating.importance'),
            preserve_default=False,
        ),
    ]
