# Generated by Django 3.1.4 on 2020-12-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0009_auto_20201215_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(choices=[(0, "doesn't matter at all"), (1, 'a little'), (50, 'average'), (250, 'very important'), (999, "don't show my profile to people who selected this")], default=50)),
                ('privacy', models.IntegerField(default=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='importance',
        ),
        migrations.DeleteModel(
            name='Importance',
        ),
        migrations.AddField(
            model_name='answer',
            name='attributes',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dating.attributes'),
            preserve_default=False,
        ),
    ]
