# Generated by Django 3.1.4 on 2020-12-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0010_auto_20201215_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='attributes',
        ),
        migrations.AddField(
            model_name='choice',
            name='importance',
            field=models.IntegerField(choices=[(0, "doesn't matter at all"), (1, 'a little'), (50, 'average'), (250, 'very important'), (999, "don't show my profile to people who selected this")], default=50),
        ),
        migrations.AddField(
            model_name='choice',
            name='privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
    ]
