# Generated by Django 3.1.4 on 2020-12-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0014_auto_20201215_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='privacy',
        ),
        migrations.AddField(
            model_name='answer',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
