# Generated by Django 3.1.4 on 2020-12-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0015_auto_20201215_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='public',
        ),
        migrations.AddField(
            model_name='answer',
            name='public_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='public_self',
            field=models.BooleanField(default=False),
        ),
    ]
