# Generated by Django 3.1.4 on 2020-12-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0016_auto_20201216_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_self',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dating.choice'),
        ),
    ]
