# Generated by Django 3.1.4 on 2020-12-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0017_auto_20201216_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
    ]
